name: CI

on:
     push:
          branches:
               - main
     pull_request:
          branches:
               - main

env:
     CARGO_TERM_COLOR: always

jobs:
     format:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v3
               - uses: actions-rs/toolchain@v1
                 with:
                      toolchain: stable

               - run: cargo fmt --all -- --check
     test:
          name: lib tests and docs test
          runs-on: ubuntu-latest

          steps:
               - uses: actions/checkout@v3
               - uses: actions-rs/toolchain@v1
                 with:
                      toolchain: stable
               - uses: actions/cache@v3
                 with:
                      path: |
                           ~/.cargo/bin/
                           ~/.cargo/registry/index/
                           ~/.cargo/registry/cache/
                           ~/.cargo/git/db/
                           target/
                      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
               - run: cargo test -r  --all-features

     rust-clippy-analyze:
          runs-on: ubuntu-latest
          permissions:
               contents: read
               security-events: write
               actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
          steps:
               - name: Checkout code
                 uses: actions/checkout@v3

               - name: Install Rust toolchain
                 uses: actions-rs/toolchain@v1
                 with:
                      profile: minimal
                      toolchain: stable
                      components: clippy
                      override: true
               - uses: actions/cache@v3
                 with:
                      path: |
                           ~/.cargo/bin/
                           ~/.cargo/registry/index/
                           ~/.cargo/registry/cache/
                           ~/.cargo/git/db/
                           target/
                      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-clippy

               - name: Install required cargo
                 run: cargo install clippy-sarif sarif-fmt || true

               - name: Run rust-clippy
                 run: cargo clippy
                      --all-features
                      --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
                 continue-on-error: true

               - name: Upload analysis results to GitHub
                 uses: github/codeql-action/upload-sarif@v2
                 with:
                      sarif_file: rust-clippy-results.sarif
                      wait-for-processing: true
